name: flutter_freedome
description: Унифицированная Flutter библиотека для интеграции с купольными кинотеатрами FreeDome
license: NativeMindNONC
version: 2.1.1+108
homepage: https://github.com/nativemind/flutter_freedome

# 2025 Best Practice: Минимальная версия SDK для новых фич и безопасности
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Web support
  flutter_web_plugins:
    sdk: flutter
  
  # Platform Interface
  plugin_platform_interface: ^2.1.8
  
  # FreeDome packages (temporarily disabled for publication)
  # flutter_freedome_connectivity: any
  # flutter_freedome_calibration: any
  
  # HTTP Client & WebSocket (2025 latest versions)
  dio: ^5.9.0
  http: ^1.5.0
  web_socket_channel: ^3.0.1
  socket_io_client: ^3.1.2
  
  # State Management
  provider: ^6.1.5
  
  # JSON Serialization (latest compatible versions)
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  
  # Local Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.2
  # isar: ^3.1.0+1  # Temporarily disabled due to Android namespace issues
  # isar_flutter_libs: ^3.1.0+1

  # Network Connectivity
  connectivity_plus: ^7.0.0
  
  # Security & Crypto
  crypto: ^3.0.6
  
  # Logging
  logger: ^2.6.1
  
  # Math & Geometry
  vector_math: ^2.1.4
  
  # Sensors
  sensors_plus: ^6.0.1
  
  # Audio
  just_audio: ^0.9.41
  audio_session: ^0.1.21
  
  # Device Info
  device_info_plus: ^12.1.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # File Operations
  path_provider: ^2.1.5
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation (latest compatible versions)
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  # isar_generator: ^3.1.0+1  # Temporarily disabled due to Android namespace issues
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Testing (latest versions)
  mocktail: ^1.0.4
  
  # Coverage
  coverage: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.nativemind.flutter.freedome.flutter_freedome
        pluginClass: FlutterFreedomePlugin
      ios:
        pluginClass: FlutterFreedomePlugin
      linux:
        pluginClass: FlutterFreedomePlugin
      macos:
        pluginClass: FlutterFreedomePlugin
      windows:
        pluginClass: FlutterFreedomePlugin
      web:
        pluginClass: FlutterFreedomeWeb
        fileName: flutter_freedome_web.dart

  assets:
    - assets/localization/
