name: flutter_freedome
description: Унифицированная Flutter библиотека для интеграции с купольными кинотеатрами FreeDome
license: NativeMindNONC
version: 2.0.0+1
homepage: https://github.com/nativemind/flutter_freedome

# 2025 Best Practice: Минимальная версия SDK для новых фич и безопасности
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Web support
  flutter_web_plugins:
    sdk: flutter
  
  # Platform Interface
  plugin_platform_interface: ^2.1.8
  
  # FreeDome packages
  flutter_freedome_connectivity:
    path: ../flutter_freedome_connectivity
  flutter_freedome_calibration:
    path: ../flutter_freedome_calibration
  
  # HTTP Client & WebSocket (2025 лучшие практики)
  dio: ^5.6.0
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  socket_io_client: ^3.1.2
  
  # State Management
  provider: ^6.1.2
  
  # JSON Serialization (совместимые версии)
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.4.0
  # isar: ^3.1.0+1  # Временно отключено из-за проблем с Android namespace
  # isar_flutter_libs: ^3.1.0+1
 
  # Network Connectivity
  connectivity_plus: ^6.1.0
  
  # Security & Crypto
  crypto: ^3.0.5
  
  # Logging
  logger: ^2.4.0
  
  # Math & Geometry
  vector_math: ^2.1.4
  
  # Sensors
  sensors_plus: ^6.0.1
  
  # Audio
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  
  # Device Info
  device_info_plus: ^12.0.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # File Operations
  path_provider: ^2.1.4
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation (совместимые версии)
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.2  # Понижаем версию для совместимости
  # isar_generator: ^3.1.0+1  # Временно отключено из-за проблем с Android namespace
  
  # Linting
  flutter_lints: ^5.0.0
  
  # Testing (решаем конфликт зависимостей)
  mocktail: ^1.0.4
  
  # Coverage
  coverage: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        package: ru.nativemind.flutter.freedome.flutter_freedome
        pluginClass: FlutterFreedomePlugin
      ios:
        pluginClass: FlutterFreedomePlugin
      linux:
        pluginClass: FlutterFreedomePlugin
      macos:
        pluginClass: FlutterFreedomePlugin
      windows:
        pluginClass: FlutterFreedomePlugin
      web:
        pluginClass: FlutterFreedomeWeb
        fileName: flutter_freedome_web.dart

  assets:
    - assets/localization/
