name: flutter_freedome
description: Унифицированная Flutter библиотека для интеграции с купольными кинотеатрами FreeDome
license: NativeMindNONC
version: 1.2.0+3
homepage: https://github.com/nativemind/flutter_freedome

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Web support
  flutter_web_plugins:
    sdk: flutter
  
  # Platform Interface
  plugin_platform_interface: ^2.1.7
  
  # HTTP Client & WebSocket
  dio: ^5.4.3
  http: ^1.2.1
  web_socket_channel: ^3.0.3
  socket_io_client: ^2.0.3+1
  
  # State Management
  provider: ^6.1.1
  
  # JSON Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network Connectivity
  connectivity_plus: ^6.0.5
  
  # Security & Crypto
  crypto: ^3.0.3
  
  # Logging
  logger: ^2.0.2+1
  
  # Math & Geometry
  vector_math: ^2.1.4
  
  # Sensors
  sensors_plus: ^4.0.2
  
  # Audio
  just_audio: ^0.9.37
  audio_session: ^0.1.25
  
  # Device Info
  device_info_plus: ^12.1.0
  
  # Permissions
  permission_handler: ^11.3.0
  
  # File Operations
  path_provider: ^2.1.2
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  test: ^1.24.9
  
  # Test coverage
  coverage: ^1.9.2
  test_coverage: ^0.5.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.nativemind.flutter.freedome.flutter_freedome
        pluginClass: FlutterFreedomePlugin
      ios:
        pluginClass: FlutterFreedomePlugin
      linux:
        pluginClass: FlutterFreedomePlugin
      macos:
        pluginClass: FlutterFreedomePlugin
      windows:
        pluginClass: FlutterFreedomePlugin
      web:
        pluginClass: FlutterFreedomeWeb
        fileName: flutter_freedome_web.dart

  assets:
    - assets/localization/